projects:
  - id: lokalstore
    name: LokalStore
    components:
      - id: admin
        name: Admin
        path: 'C:\Projects\LokalStore\Admin'
        build_command: npm run build
        output_directory: build
        package_enabled: true
        package_filename: lokalstore-admin.zip
      - id: customer
        name: Customer
        path: 'C:\Projects\LokalStore\Customer'
        build_command: npm run build
        output_directory: build
        package_enabled: true
        package_filename: lokalstore-customer.zip
      - id: merchant
        name: Merchant
        path: 'C:\Projects\LokalStore\Merchant'
        build_command: npm run build
        output_directory: build
        package_enabled: true
        package_filename: lokalstore-merchant.zip
      - id: affiliate
        name: Affiliate
        path: 'C:\Projects\LokalStore\Affiliate'
        build_command: npm run build
        output_directory: build
        package_enabled: true
        package_filename: lokalstore-affiliate.zip
