// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildRunning() {
  return window['go']['app']['App']['BuildRunning']();
}

export function CancelBuild(arg1) {
  return window['go']['app']['App']['CancelBuild'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['app']['App']['DeleteProject'](arg1);
}

export function GetDaliConfig() {
  return window['go']['app']['App']['GetDaliConfig']();
}

export function GetPackagePlan(arg1) {
  return window['go']['app']['App']['GetPackagePlan'](arg1);
}

export function GetProject(arg1) {
  return window['go']['app']['App']['GetProject'](arg1);
}

export function GetProjects() {
  return window['go']['app']['App']['GetProjects']();
}

export function GetTransferPlan(arg1) {
  return window['go']['app']['App']['GetTransferPlan'](arg1);
}

export function PickDirectory(arg1) {
  return window['go']['app']['App']['PickDirectory'](arg1);
}

export function PickFile(arg1) {
  return window['go']['app']['App']['PickFile'](arg1);
}

export function SaveDaliConfig(arg1) {
  return window['go']['app']['App']['SaveDaliConfig'](arg1);
}

export function SaveProject(arg1) {
  return window['go']['app']['App']['SaveProject'](arg1);
}

export function StartBuild(arg1) {
  return window['go']['app']['App']['StartBuild'](arg1);
}

export function StartBuildAndPackage(arg1) {
  return window['go']['app']['App']['StartBuildAndPackage'](arg1);
}

export function StartBuildPackageAndSend(arg1) {
  return window['go']['app']['App']['StartBuildPackageAndSend'](arg1);
}

export function StartPackage(arg1) {
  return window['go']['app']['App']['StartPackage'](arg1);
}

export function StartTransfer(arg1) {
  return window['go']['app']['App']['StartTransfer'](arg1);
}

export function ValidateProject(arg1) {
  return window['go']['app']['App']['ValidateProject'](arg1);
}
