// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function DeleteProject(arg1:string):Promise<void>;

export function GetProject(arg1:string):Promise<models.Project>;

export function GetProjects():Promise<Array<models.Project>>;

export function SaveProject(arg1:models.Project):Promise<models.Project>;

export function ValidateProject(arg1:models.Project):Promise<Array<models.ValidationIssue>>;
