// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteProject(arg1) {
  return window['go']['app']['App']['DeleteProject'](arg1);
}

export function GetProject(arg1) {
  return window['go']['app']['App']['GetProject'](arg1);
}

export function GetProjects() {
  return window['go']['app']['App']['GetProjects']();
}

export function SaveProject(arg1) {
  return window['go']['app']['App']['SaveProject'](arg1);
}

export function ValidateProject(arg1) {
  return window['go']['app']['App']['ValidateProject'](arg1);
}
