// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function BuildRunning():Promise<boolean>;

export function CancelBuild(arg1:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function GetDaliConfig():Promise<models.DaliConfig>;

export function GetPackagePlan(arg1:models.PackageRequest):Promise<models.PackagePlan>;

export function GetProject(arg1:string):Promise<models.Project>;

export function GetProjects():Promise<Array<models.Project>>;

export function GetTransferPlan(arg1:models.TransferRequest):Promise<models.TransferPlan>;

export function PickDirectory(arg1:string):Promise<string>;

export function PickFile(arg1:string):Promise<string>;

export function SaveDaliConfig(arg1:models.DaliConfig):Promise<models.DaliConfig>;

export function SaveProject(arg1:models.Project):Promise<models.Project>;

export function StartBuild(arg1:models.BuildRequest):Promise<models.BuildRun>;

export function StartBuildAndPackage(arg1:models.PackageRequest):Promise<models.ReleaseRun>;

export function StartBuildPackageAndSend(arg1:models.PackageRequest):Promise<models.ReleaseRun>;

export function StartPackage(arg1:models.PackageRequest):Promise<models.PackageRun>;

export function StartTransfer(arg1:models.TransferRequest):Promise<models.TransferRun>;

export function ValidateProject(arg1:models.Project):Promise<Array<models.ValidationIssue>>;
